package com.viettel.model;
// Generated Mar 13, 2017 5:50:39 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppGroupIsimIbm generated by hbm2java
 */
@Entity
@Table(name = "APP_GROUP_ISIM_IBM")
public class AppGroupIsimIbm implements java.io.Serializable {

	private long appGroupId;
	private String productCode;
	private String pm;

	public AppGroupIsimIbm() {
	}

	public AppGroupIsimIbm(long appGroupId, String productCode) {
		this.appGroupId = appGroupId;
		this.productCode = productCode;
	}

	public AppGroupIsimIbm(long appGroupId, String productCode, String pm) {
		this.appGroupId = appGroupId;
		this.productCode = productCode;
		this.pm = pm;
	}

	@Id

	@Column(name = "APP_GROUP_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getAppGroupId() {
		return this.appGroupId;
	}

	public void setAppGroupId(long appGroupId) {
		this.appGroupId = appGroupId;
	}

	@Column(name = "PRODUCT_CODE", nullable = false, length = 200)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "PM", length = 200)
	public String getPm() {
		return this.pm;
	}

	public void setPm(String pm) {
		this.pm = pm;
	}

}
