package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0
import static javax.persistence.GenerationType.SEQUENCE;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.viettel.it.util.MyLinkedList;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "ACTION_DB_SERVER")
public class Action implements java.io.Serializable {

	private Long actionId;
	private Action action;
	private String name;
	private String description;
	private String itbusinessType;
	private Long serviceBusinessId;
	private Long treeLevel;
	private String openBlockGroup;
	private Long provisioningType;

	private List<ActionOfFlow> actionOfFlows = new ArrayList<ActionOfFlow>(0);
	private List<ActionDetail> actionDetails = new ArrayList<ActionDetail>(0);
	private List<Action> actions = new ArrayList<Action>(0);

	private List<ItUserAction> userActions = new ArrayList<ItUserAction>(0);
	private List<ItNodeAction> nodeActions = new ArrayList<ItNodeAction>(0);

	/**
	 * For export
	 */
	private List<String> commandExecutes = new MyLinkedList<String>();
	private List<String> commandRollbacks = new MyLinkedList<String>();
	private List<CommandDetail> lstCmdDetailExec = new MyLinkedList<CommandDetail>();
	private List<CommandDetail> lstCmdDetailRollback = new MyLinkedList<CommandDetail>();
	private String nameRollback;
	private Long status;



	/**
	 * For tree
	 */
	private boolean expanded = false;
	public Action() {
	}

//	public Action(Long actionId) {
//		this.actionId = actionId;
//	}
//
//	public Action(Long actionId, Action action, String name, String description, List<ActionOfFlow> actionOfFlows, List<ActionDetail> actionDetails, List<Action> actions) {
//		this.actionId = actionId;
//		this.action = action;
//		this.name = name;
//		this.description = description;
//		this.actionOfFlows = actionOfFlows;
//		this.actionDetails = actionDetails;
//		this.actions = actions;
//	}


    @Id
    @Column(name = "ACTION_ID", unique = true, nullable = false, precision = 12, scale = 0)
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @SequenceGenerator(name = "generator", sequenceName = "ACTION_DB_SERVER_SEQ", allocationSize = 1)
    public Long getActionId() {
        return this.actionId;
    }

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PARENT_ID")
	public Action getAction() {
		return this.action;
	}

    public void setAction(Action action) {
        this.action = action;
    }

    @Column(name = "NAME", length = 500)
    public String getName() {
        return this.name;
    }

	public Long getStatus() {
		return status;
	}
	@Column(name = "STATUS", length = 12)
	public void setStatus(Long status) {
		this.status = status;
	}

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 500)
    public String getDescription() {
        return this.description;
    }

	@Column(name = "ITBUSINESS_TYPE", length = 200)
	public String getItbusinessType() {
		return itbusinessType;
	}

	public void setItbusinessType(String itbusinessType) {
		this.itbusinessType = itbusinessType;
	}

	@Column(name = "SERVICE_BUSINESS_ID", precision = 12, scale = 0)
	public Long getServiceBusinessId() {
		return serviceBusinessId;
	}

	public void setServiceBusinessId(Long serviceBusinessId) {
		this.serviceBusinessId = serviceBusinessId;
	}

	@Column(name = "TREE_LEVEL", precision = 12, scale = 0)
	public Long getTreeLevel() {
		return treeLevel;
	}

	public void setTreeLevel(Long treeLevel) {
		this.treeLevel = treeLevel;
	}

	@Fetch(FetchMode.SELECT)
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "action")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public List<ActionOfFlow> getActionOfFlows() {
		return this.actionOfFlows;
	}

	@Fetch(FetchMode.SELECT)
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "action")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public List<ActionDetail> getActionDetails() {
		return this.actionDetails;
	}

	@Fetch(FetchMode.SELECT)
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "action")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public List<Action> getActions() {
		return this.actions;
	}

	@Fetch(FetchMode.SELECT)
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "actionUser")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public List<ItUserAction> getUserActions() {
		return userActions;
	}

	@Fetch(FetchMode.SELECT)
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "actionNode")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public List<ItNodeAction> getNodeActions() {
		return nodeActions;
	}

	@Column(name = "OPEN_BLOCK_GROUP", length = 200)
	public String getOpenBlockGroup() {
		return openBlockGroup;
	}

	public void setOpenBlockGroup(String openBlockGroup) {
		this.openBlockGroup = openBlockGroup;
	}

	@Column(name = "PROVISIONING_TYPE", precision = 12, scale = 0)
	public Long getProvisioningType() {
		return provisioningType;
	}

	public void setProvisioningType(Long provisioningType) {
		this.provisioningType = provisioningType;
	}

	public void setNodeActions(List<ItNodeAction> nodeActions) {
		this.nodeActions = nodeActions;
	}

	public void setUserActions(List<ItUserAction> userActions) {
		this.userActions = userActions;
	}

	@Transient
	public List<String> getCommandExecutes() {
		return commandExecutes;
	}

	public void setCommandExecutes(List<String> commandExecutes) {
		this.commandExecutes = commandExecutes;
	}

	@Transient
	public List<String> getCommandRollbacks() {
		return commandRollbacks;
	}

	public void setCommandRollbacks(List<String> commandRollbacks) {
		this.commandRollbacks = commandRollbacks;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setActionOfFlows(List<ActionOfFlow> actionOfFlows) {
		this.actionOfFlows = actionOfFlows;
	}

	public void setActionDetails(List<ActionDetail> actionDetails) {
		this.actionDetails = actionDetails;
	}

	public void setActions(List<Action> actions) {
		this.actions = actions;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actionId == null) ? 0 : actionId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Action other = (Action) obj;
		if (actionId == null) {
			if (other.actionId != null)
				return false;
		} else if (!actionId.equals(other.actionId))
			return false;
		return true;
	}
	public int compareTo(Action action) {
        return this.getActionId().compareTo(action.getActionId());
    }

	@Transient
	public boolean isExpanded() {
		return expanded;
	}

	public void setExpanded(boolean expanded) {
		this.expanded = expanded;
	}

	@Transient
	public String getNameRollback() {
		return nameRollback;
	}

	public void setNameRollback(String nameRollback) {
		this.nameRollback = nameRollback;
	}

	@Transient
	public List<CommandDetail> getLstCmdDetailExec() {
		return lstCmdDetailExec;
	}

	public void setLstCmdDetailExec(List<CommandDetail> lstCmdDetailExec) {
		this.lstCmdDetailExec = lstCmdDetailExec;
	}

	@Transient
	public List<CommandDetail> getLstCmdDetailRollback() {
		return lstCmdDetailRollback;
	}

	public void setLstCmdDetailRollback(List<CommandDetail> lstCmdDetailRollback) {
		this.lstCmdDetailRollback = lstCmdDetailRollback;
	}


	//	@Override
	public String toString() {
		return "Action{" +
				"actionId=" + actionId +
				", name='" + name + '\'' +
				", description='" + description + '\'' +
				", itbusinessType='" + itbusinessType + '\'' +
				", serviceBusinessId=" + serviceBusinessId +
				", treeLevel=" + treeLevel +
				'}';
	}

}
