package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import com.itextpdf.kernel.log.SystemOutCounter;
import com.viettel.it.persistence.AutoMopParamsServiceImpl;
import com.viettel.it.util.PasswordEncoder;

import javax.persistence.*;
import java.util.List;

/**
 * FlowRunAction generated by hbm2java
 */
@Entity
@Table(name = "AUTO_CONFIG_MOP_PARAMS" )
public class AutoConfigMopParams implements java.io.Serializable {

    private AutoConfigMopParamsId id;
    private FlowTemplates flowTemplateId;
    private String nocproParamLabel;
    private String regexPaser;


    public AutoConfigMopParams(AutoConfigMopParamsId id, String nocproParamLabel, String regexPaser) {
        this.id = id;
        this.nocproParamLabel = nocproParamLabel;
        this.regexPaser = regexPaser;
    }

    public AutoConfigMopParams() {
    }

    public AutoConfigMopParams(AutoConfigMopParamsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "flowTemplateId", column = @Column(name = "FLOW_TEMPLATE_ID", nullable = false, precision = 22, scale = 0)),
            @AttributeOverride(name = "paramCode", column = @Column(name = "PARAM_CODE", nullable = false, precision = 22, scale = 0))})
    public AutoConfigMopParamsId getId() {
        return id;
    }

    public void setId(AutoConfigMopParamsId id) {
        this.id = id;
    }

    @Column(name = "NOCPRO_PARAM_LABEL", nullable = true, length = 200)
    public String getNocproParamLabel() {
        return nocproParamLabel;
    }

    public void setNocproParamLabel(String nocproParamLabel) {
        this.nocproParamLabel = nocproParamLabel;
    }

    @Column(name = "REGEX_PASER", nullable = true, length = 200)
    public String getRegexPaser() {
        return regexPaser;
    }

    public void setRegexPaser(String regexPaser) {
        this.regexPaser = regexPaser;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "FLOW_TEMPLATE_ID", nullable = false, insertable = false, updatable = false)
    public FlowTemplates getFlowTemplateId() {
        return flowTemplateId;
    }

    public void setFlowTemplateId(FlowTemplates flowTemplateId) {
        this.flowTemplateId = flowTemplateId;
    }

    public static void main(String args[]) {
        try {
            List<AutoConfigMopParams> configMops = new AutoMopParamsServiceImpl().findList();
            System.out.println(configMops.size());
            System.out.println(configMops.get(0).getId().getFlowTemplateId());
            System.out.println(configMops.get(0).getFlowTemplateId().getFlowTemplateName());
            System.out.println(configMops.get(0).getNocproParamLabel());
            System.out.println(configMops.get(0).getRegexPaser());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
