package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import com.viettel.it.persistence.FlowRunActionServiceImpl;
import com.viettel.it.util.Config;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.primefaces.model.UploadedFile;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * FlowRunAction generated by hbm2java
 */
@Embeddable
public class AutoConfigMopParamsId implements java.io.Serializable {

    private Long flowTemplateId;
    private String paramCode;

    public AutoConfigMopParamsId() {
    }

    public AutoConfigMopParamsId(Long flowTemplateId, String paramCode) {
        this.flowTemplateId = flowTemplateId;
        this.paramCode = paramCode;
    }

    @Column(name = "FLOW_TEMPLATE_ID", nullable = false, precision = 22, scale = 0)
    public Long getFlowTemplateId() {
        return flowTemplateId;
    }

    public void setFlowTemplateId(Long flowTemplateId) {
        this.flowTemplateId = flowTemplateId;
    }

    @Column(name = "PARAM_INPUT_ID", nullable = false, length = 200)
    public String getParamCode() {
        return paramCode;
    }

    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AutoConfigMopParamsId that = (AutoConfigMopParamsId) o;

        if (!flowTemplateId.equals(that.flowTemplateId)) return false;
        return paramCode.equals(that.paramCode);
    }

    @Override
    public int hashCode() {
        int result = flowTemplateId.hashCode();
        result = 31 * result + paramCode.hashCode();
        return result;
    }
}
