package com.viettel.it.model;
// Generated Jul 12, 2011 2:20:03 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdmFuncQueryButtonId generated by hbm2java
 */
@Embeddable
public class CatConfigId implements java.io.Serializable {

    private String configGroup;
    private String propertyKey;
    public CatConfigId id;

    public CatConfigId() {
    }

    public CatConfigId(String configGroup, String propertyKey) {
        this.configGroup = configGroup;
        this.propertyKey = propertyKey;
    }

    @Column(name = "CONFIG_GROUP", nullable = false, length = 50)
    public String getConfigGroup() {
        return configGroup;
    }

    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup;
    }

    @Column(name = "PROPERTY_KEY", nullable = false, length = 50)
    public String getPropertyKey() {
        return propertyKey;
    }

    public void setPropertyKey(String propertyKey) {
        this.propertyKey = propertyKey;
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int hashCode() {
        return super.hashCode(); //To change body of generated methods, choose Tools | Templates.
    }
    
}
