package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * CommandTelnetParser generated by hbm2java
 */
@Entity
@Table(name = "COMMAND_TELNET_PARSER")
public class CommandTelnetParser implements java.io.Serializable {

	private Long telnetParserId;
	private String cmd;
	private String cmdEnd;
	private Long cmdTimeout;
	private String rowStart;
	private Long rowOutput;
	private String splitColumnRegex;
	private Long columnOutput;
	private Long countRow;
	private String rowEnd;
	private String regexOutput;
	private String pagingRegex;
	private String pagingCmd;
	private String rowStartOperator;
	private String rowEndOperator;
    private String confirmRegex;
	private String confirmCmd;
	private List<CommandDetail> commandDetails = new ArrayList<CommandDetail>(0);

    public CommandTelnetParser() {
    }

    public CommandTelnetParser(Long telnetParserId, String cmd, String cmdEnd) {
        this.telnetParserId = telnetParserId;
        this.cmd = cmd;
        this.cmdEnd = cmdEnd;
    }

    public CommandTelnetParser(Long telnetParserId, String cmd, String cmdEnd, Long cmdTimeout, String rowStart, Long rowOutput, String splitColumnRegex, Long columnOutput, Long countRow,
            String rowEnd, String regexOutput, String pagingRegex, String pagingCmd, List<CommandDetail> commandDetails) {
        this.telnetParserId = telnetParserId;
        this.cmd = cmd;
        this.cmdEnd = cmdEnd;
        this.cmdTimeout = cmdTimeout;
        this.rowStart = rowStart;
        this.rowOutput = rowOutput;
        this.splitColumnRegex = splitColumnRegex;
        this.columnOutput = columnOutput;
        this.countRow = countRow;
        this.rowEnd = rowEnd;
        this.regexOutput = regexOutput;
        this.pagingRegex = pagingRegex;
        this.pagingCmd = pagingCmd;
        this.commandDetails = commandDetails;
    }

    @Id
    @Column(name = "TELNET_PARSER_ID", unique = true, nullable = false, precision = 10, scale = 0)
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @SequenceGenerator(name = "generator", sequenceName = "COMMAND_TELNET_PARSER_seq", allocationSize = 1)
    public Long getTelnetParserId() {
        return this.telnetParserId;
    }

    public void setTelnetParserId(Long telnetParserId) {
        this.telnetParserId = telnetParserId;
    }

    @Column(name = "CMD", nullable = false, length = 500)
    public String getCmd() {
        return this.cmd;
    }

    public void setCmd(String cmd) {
        this.cmd = cmd;
    }

    @Column(name = "CMD_END", nullable = false, length = 100)
    public String getCmdEnd() {
        return this.cmdEnd;
    }

    public void setCmdEnd(String cmdEnd) {
        this.cmdEnd = cmdEnd;
    }

    @Column(name = "CMD_TIMEOUT", precision = 3, scale = 0)
    public Long getCmdTimeout() {
        return this.cmdTimeout;
    }

    public void setCmdTimeout(Long cmdTimeout) {
        this.cmdTimeout = cmdTimeout;
    }

    @Column(name = "ROW_START", length = 500)
    public String getRowStart() {
        return this.rowStart;
    }

    public void setRowStart(String rowStart) {
        this.rowStart = rowStart;
    }

    @Column(name = "ROW_OUTPUT", precision = 5, scale = 0)
    public Long getRowOutput() {
        return this.rowOutput;
    }

    public void setRowOutput(Long rowOutput) {
        this.rowOutput = rowOutput;
    }

    @Column(name = "SPLIT_COLUMN_REGEX", length = 500)
    public String getSplitColumnRegex() {
        return this.splitColumnRegex;
    }

    public void setSplitColumnRegex(String splitColumnRegex) {
        this.splitColumnRegex = splitColumnRegex;
    }

    @Column(name = "COLUMN_OUTPUT", precision = 5, scale = 0)
    public Long getColumnOutput() {
        return this.columnOutput;
    }

    public void setColumnOutput(Long columnOutput) {
        this.columnOutput = columnOutput;
    }

    @Column(name = "COUNT_ROW", precision = 5, scale = 0)
    public Long getCountRow() {
        return this.countRow;
    }

    public void setCountRow(Long countRow) {
        this.countRow = countRow;
    }

    @Column(name = "ROW_END", length = 500)
    public String getRowEnd() {
        return this.rowEnd;
    }

    public void setRowEnd(String rowEnd) {
        this.rowEnd = rowEnd;
    }

    @Column(name = "REGEX_OUTPUT", length = 500)
    public String getRegexOutput() {
        return this.regexOutput;
    }

    public void setRegexOutput(String regexOutput) {
        this.regexOutput = regexOutput;
    }

    @Column(name = "PAGING_REGEX", length = 500)
    public String getPagingRegex() {
        return this.pagingRegex;
    }

    public void setPagingRegex(String pagingRegex) {
        this.pagingRegex = pagingRegex;
    }

    @Column(name = "PAGING_CMD", length = 100)
    public String getPagingCmd() {
        return this.pagingCmd;
    }

    public void setPagingCmd(String pagingCmd) {
        this.pagingCmd = pagingCmd;
    }

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "commandTelnetParser")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public List<CommandDetail> getCommandDetails() {
		return this.commandDetails;
	}

    public void setCommandDetails(List<CommandDetail> commandDetails) {
        this.commandDetails = commandDetails;
    }

    @Column(name = "ROW_START_OPERATOR")
    public String getRowStartOperator() {
        return rowStartOperator;
    }

    public void setRowStartOperator(String rowStartOperator) {
        this.rowStartOperator = rowStartOperator;
    }

    @Column(name = "ROW_END_OPERATOR")
    public String getRowEndOperator() {
        return rowEndOperator;
    }

    public void setRowEndOperator(String rowEndOperator) {
        this.rowEndOperator = rowEndOperator;
    }
    
    @Column(name = "CONFIRM_REGEX", length = 500)
    public String getConfirmRegex() {
        return confirmRegex;
    }

    public void setConfirmRegex(String confirmRegex) {
        this.confirmRegex = confirmRegex;
    }

    @Column(name = "CONFIRM_CMD", length = 100)
    public String getConfirmCmd() {
        return confirmCmd;
    }

    public void setConfirmCmd(String confirmCmd) {
        this.confirmCmd = confirmCmd;
    }
}
