package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "DB_PARAM_DATAFILE")
public class DbParamDatafile implements java.io.Serializable {

	private Long paramDatafileId;
	private String dirDetail;
	private Long dbId;
	private String dbIp;
	private String dbName;
	private String datafileDir;
	private String dirType;
	private Integer dirSize;
	private String datafileSize;
	private String autoExtend;
	private String initialSize;
	private String maxSize;
	private Integer status;
	private Date inserTime;
	private Date updateTime;
	
	public DbParamDatafile() {
		super();
	}

	public DbParamDatafile(String dirDetail, Long dbId, String dbIp,
			String dbName, String datafileDir, String dirType, Integer dirSize,
			String datafileSize, String autoExtend, String initialSize,
			String maxSize, Integer status) {
		super();
		this.dirDetail = dirDetail;
		this.dbId = dbId;
		this.dbIp = dbIp;
		this.dbName = dbName;
		this.datafileDir = datafileDir;
		this.dirType = dirType;
		this.dirSize = dirSize;
		this.datafileSize = datafileSize;
		this.autoExtend = autoExtend;
		this.initialSize = initialSize;
		this.maxSize = maxSize;
		this.status = status;
	}

	
	@Column(name = "DIR_DETAIL", length = 200)
	public String getDirDetail() {
		return dirDetail;
	}

	public void setDirDetail(String dirDetail) {
		this.dirDetail = dirDetail;
	}

	@Column(name = "DB_ID", precision = 22, scale = 0)
	public Long getDbId() {
		return dbId;
	}

	public void setDbId(Long dbId) {
		this.dbId = dbId;
	}

	@Column(name = "DB_IP", length = 200)
	public String getDbIp() {
		return dbIp;
	}

	public void setDbIp(String dbIp) {
		this.dbIp = dbIp;
	}

	@Column(name = "DB_NAME", length = 200)
	public String getDbName() {
		return dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	@Column(name = "DATAFILE_DIR", length = 200)
	public String getDatafileDir() {
		return datafileDir;
	}

	public void setDatafileDir(String datafileDir) {
		this.datafileDir = datafileDir;
	}

	@Column(name = "DIR_TYPE", length = 200)
	public String getDirType() {
		return dirType;
	}

	public void setDirType(String dirType) {
		this.dirType = dirType;
	}

	@Column(name = "DIR_SIZE", precision = 6, scale = 0)
	public Integer getDirSize() {
		return dirSize;
	}

	public void setDirSize(Integer dirSize) {
		this.dirSize = dirSize;
	}

	@Column(name = "DATAFILE_SIZE", length = 200)
	public String getDatafileSize() {
		return datafileSize;
	}

	public void setDatafileSize(String datafileSize) {
		this.datafileSize = datafileSize;
	}

	
	@Column(name = "AUTO_EXTEND", precision = 6, scale = 0)
	public String getAutoExtend() {
		return autoExtend;
	}

	public void setAutoExtend(String autoExtend) {
		this.autoExtend = autoExtend;
	}

	@Column(name = "INITIAL_SIZE", length = 200)
	public String getInitialSize() {
		return initialSize;
	}

	public void setInitialSize(String initialSize) {
		this.initialSize = initialSize;
	}

	@Column(name = "MAX_SIZE", length = 200)
	public String getMaxSize() {
		return maxSize;
	}

	public void setMaxSize(String maxSize) {
		this.maxSize = maxSize;
	}

	@Column(name = "STATUS", precision = 6, scale = 0)
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Id
	@Column(name = "PARAM_DATAFILE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @SequenceGenerator(name = "generator", sequenceName = "PARAM_DATAFILE_ID_SEQ", allocationSize = 1)
	public Long getParamDatafileId() {
		return paramDatafileId;
	}

	public void setParamDatafileId(Long paramDatafileId) {
		this.paramDatafileId = paramDatafileId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_TIME", length = 7)
	public Date getInserTime() {
		return inserTime;
	}

	public void setInserTime(Date inserTime) {
		this.inserTime = inserTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 7)
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
