package com.viettel.it.model;

// Generated Sep 27, 2016 11:33:18 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * FlowRunLog generated by hbm2java
 */
@Entity
@Table(name = "FLOW_RUN_LOG")
public class FlowRunLog implements java.io.Serializable {

	private Long flowRunLogId;
	private Long actionOfFlowId;
	private String username;
	private String account;
	private Date createTime;
	private Date finishTime;
	private Long flowRunId;
    private String logFilePath;
    private Long actionOfFlowIdEnd;
	private byte[] logFileContent;

	public FlowRunLog() {
	}

	public FlowRunLog(Long flowRunLogId, Long actionOfFlowId, String username, String account, Long flowRunId) {
		this.flowRunLogId = flowRunLogId;
		this.actionOfFlowId = actionOfFlowId;
		this.username = username;
		this.account = account;
		this.flowRunId = flowRunId;
	}

	public FlowRunLog(Long flowRunLogId, Long actionOfFlowId, String username, String account, Date createTime, Date finishTime, Long flowRunId) {
		this.flowRunLogId = flowRunLogId;
		this.actionOfFlowId = actionOfFlowId;
		this.username = username;
		this.account = account;
		this.createTime = createTime;
		this.finishTime = finishTime;
		this.flowRunId = flowRunId;
	}

	@Id
	@Column(name = "FLOW_RUN_LOG_ID", unique = true, nullable = false, precision = 20, scale = 0)
        @GeneratedValue(strategy = SEQUENCE, generator = "generator")
        @SequenceGenerator(name = "generator", sequenceName = "FLOW_RUN_LOG_seq", allocationSize = 1)
	public Long getFlowRunLogId() {
		return this.flowRunLogId;
	}

	public void setFlowRunLogId(Long flowRunLogId) {
		this.flowRunLogId = flowRunLogId;
	}

	@Column(name = "ACTION_OF_FLOW_ID", nullable = false, precision = 22, scale = 0)
	public Long getActionOfFlowId() {
		return this.actionOfFlowId;
	}

	public void setActionOfFlowId(Long actionOfFlowId) {
		this.actionOfFlowId = actionOfFlowId;
	}

	@Column(name = "USERNAME", nullable = false, length = 500)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "ACCOUNT", nullable = true, length = 500)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FINISH_TIME", length = 7)
	public Date getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	@Column(name = "FLOW_RUN_ID", nullable = false, precision = 20, scale = 0)
	public Long getFlowRunId() {
		return this.flowRunId;
	}

	public void setFlowRunId(Long flowRunId) {
		this.flowRunId = flowRunId;
	}
        
    @Column(name="LOG_FILE_PATH")
    public String getLogFilePath() {
        return logFilePath;
    }

    public void setLogFilePath(String logFilePath) {
        this.logFilePath = logFilePath;
    }

    @Column(name = "ACTION_OF_FLOW_ID_END", nullable = true, precision = 22, scale = 0)
    public Long getActionOfFlowIdEnd() {
        return actionOfFlowIdEnd;
    }

    public void setActionOfFlowIdEnd(Long actionOfFlowIdEnd) {
        this.actionOfFlowIdEnd = actionOfFlowIdEnd;
    }
    
    @Column(name="LOG_FILE_CONTENT")
    public byte[] getLogFileContent() {
        return logFileContent;
    }

    public void setLogFileContent(byte[] logFileContent) {
        this.logFileContent = logFileContent;
    }
}
