package com.viettel.it.model;

// Generated Sep 14, 2016 1:34:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NodeRunGroupActionId generated by hbm2java
 */
@Embeddable
public class NodeRunGroupActionId implements java.io.Serializable {

	private Long nodeId;
	private Long flowRunId;
	private Long stepNum;

	public NodeRunGroupActionId() {
	}

	public NodeRunGroupActionId(Long nodeId, Long flowRunId, Long stepNum) {
		this.nodeId = nodeId;
		this.flowRunId = flowRunId;
		this.stepNum = stepNum;
	}

	@Column(name = "NODE_ID", nullable = false, precision = 22, scale = 0)
	public Long getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "FLOW_RUN_ID", nullable = false, precision = 22, scale = 0)
	public Long getFlowRunId() {
		return this.flowRunId;
	}

	public void setFlowRunId(Long flowRunId) {
		this.flowRunId = flowRunId;
	}

	@Column(name = "STEP_NUM", nullable = false, precision = 22, scale = 0)
	public Long getStepNum() {
		return this.stepNum;
	}

	public void setStepNum(Long stepNum) {
		this.stepNum = stepNum;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NodeRunGroupActionId))
			return false;
		NodeRunGroupActionId castOther = (NodeRunGroupActionId) other;

		return ((this.getNodeId() == castOther.getNodeId()) || (this.getNodeId() != null && castOther.getNodeId() != null && this.getNodeId().equals(castOther.getNodeId())))
				&& ((this.getFlowRunId() == castOther.getFlowRunId()) || (this.getFlowRunId() != null && castOther.getFlowRunId() != null && this.getFlowRunId().equals(castOther.getFlowRunId())))
				&& ((this.getStepNum() == castOther.getStepNum()) || (this.getStepNum() != null && castOther.getStepNum() != null && this.getStepNum().equals(castOther.getStepNum())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNodeId() == null ? 0 : this.getNodeId().hashCode());
		result = 37 * result + (getFlowRunId() == null ? 0 : this.getFlowRunId().hashCode());
		result = 37 * result + (getStepNum() == null ? 0 : this.getStepNum().hashCode());
		return result;
	}

}
