package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NodeRunId generated by hbm2java
 */
@Embeddable
public class NodeRunId implements java.io.Serializable {

	private Long nodeId;
	private Long flowRunId;

	public NodeRunId() {
	}

	public NodeRunId(Long nodeId, Long flowRunId) {
		this.nodeId = nodeId;
		this.flowRunId = flowRunId;
	}

	@Column(name = "NODE_ID", nullable = false, precision = 22, scale = 0)
	public Long getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "FLOW_RUN_ID", nullable = false, precision = 22, scale = 0)
	public Long getFlowRunId() {
		return this.flowRunId;
	}

	public void setFlowRunId(Long flowRunId) {
		this.flowRunId = flowRunId;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NodeRunId))
			return false;
		NodeRunId castOther = (NodeRunId) other;

		return ((this.getNodeId() == castOther.getNodeId()) || (this.getNodeId() != null && castOther.getNodeId() != null && this.getNodeId().equals(castOther.getNodeId())))
				&& ((this.getFlowRunId() == castOther.getFlowRunId()) || (this.getFlowRunId() != null && castOther.getFlowRunId() != null && this.getFlowRunId().equals(castOther.getFlowRunId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNodeId() == null ? 0 : this.getNodeId().hashCode());
		result = 37 * result + (getFlowRunId() == null ? 0 : this.getFlowRunId().hashCode());
		return result;
	}

}
