package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * ParamGroup generated by hbm2java
 */
@Entity
@Table(name = "PARAM_GROUP")
public class ParamGroup implements java.io.Serializable {

	private ParamGroupId id;
	private ParamInput paramInput;
	private FlowTemplates flowTemplates;
	private Long groupCode;
	private String paramDefault;

	public ParamGroup() {
	}

	public ParamGroup(ParamGroupId id, ParamInput paramInput, FlowTemplates flowTemplates) {
		this.id = id;
		this.paramInput = paramInput;
		this.flowTemplates = flowTemplates;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "paramInputId", column = @Column(name = "PARAM_INPUT_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "flowTemplateId", column = @Column(name = "FLOW_TEMPLATE_ID", nullable = false, precision = 22, scale = 0))
			 })
	public ParamGroupId getId() {
		return this.id;
	}

	public void setId(ParamGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PARAM_INPUT_ID", nullable = false, insertable = false, updatable = false)
	public ParamInput getParamInput() {
		return this.paramInput;
	}

	public void setParamInput(ParamInput paramInput) {
		this.paramInput = paramInput;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FLOW_TEMPLATE_ID", nullable = false, insertable = false, updatable = false)
	public FlowTemplates getFlowTemplates() {
		return this.flowTemplates;
	}

	public void setFlowTemplates(FlowTemplates flowTemplates) {
		this.flowTemplates = flowTemplates;
	}

	@Column(name="PARAM_DEFAULT")
	public String getParamDefault() {
		return paramDefault;
	}

	public void setParamDefault(String paramDefault) {
		this.paramDefault = paramDefault;
	}
	
	@Column(name = "GROUP_CODE", precision = 22, scale = 0)
	public Long getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(Long groupCode) {
		this.groupCode = groupCode;
	}

}
