package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * ParamValue generated by hbm2java
 */
@Entity
@Table(name = "PARAM_CHECKLIST_DATABASE")
public class ParamChecklistDatabase implements java.io.Serializable {

	private Long id;
	private String paramCode;
	private Long flowRunActionId;

	public ParamChecklistDatabase() {
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @SequenceGenerator(name = "generator", sequenceName = "PARAM_CHECKLIST_DATABASE_SEQ", allocationSize = 1)
	public Long getId() {
		return this.id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PARAM_CODE", length = 200)
	public String getParamCode() {
		return paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}

	@Column(name = "FLOW_RUN_ACTION_ID", nullable = false, precision = 22, scale = 0)
	public Long getFlowRunActionId() {
		return flowRunActionId;
	}

	public void setFlowRunActionId(Long flowRunActionId) {
		this.flowRunActionId = flowRunActionId;
	}

	
}
