package com.viettel.it.model;

// Generated Sep 20, 2016 10:52:39 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParamInOutId generated by hbm2java
 */
@Embeddable
public class ParamInOutId implements java.io.Serializable {

	private Long actionCommandInputId;
	private Long paramInputId;
	private Long actionFlowInId;

	public ParamInOutId() {
	}

	public ParamInOutId(Long actionCommandInputId, Long paramInputId, Long actionFlowInId) {
		this.actionCommandInputId = actionCommandInputId;
		this.paramInputId = paramInputId;
		this.actionFlowInId = actionFlowInId;
	}

	@Column(name = "ACTION_COMMAND_INPUT_ID", nullable = false, precision = 22, scale = 0)
	public Long getActionCommandInputId() {
		return this.actionCommandInputId;
	}

	public void setActionCommandInputId(Long actionCommandInputId) {
		this.actionCommandInputId = actionCommandInputId;
	}

	@Column(name = "PARAM_INPUT_ID", nullable = false, precision = 22, scale = 0)
	public Long getParamInputId() {
		return this.paramInputId;
	}

	public void setParamInputId(Long paramInputId) {
		this.paramInputId = paramInputId;
	}

	@Column(name = "ACTION_FLOW_IN_ID", nullable = false, precision = 22, scale = 0)
	public Long getActionFlowInId() {
		return this.actionFlowInId;
	}

	public void setActionFlowInId(Long actionFlowInId) {
		this.actionFlowInId = actionFlowInId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParamInOutId))
			return false;
		ParamInOutId castOther = (ParamInOutId) other;

		return ((this.getActionCommandInputId() == castOther.getActionCommandInputId()) || (this.getActionCommandInputId() != null && castOther.getActionCommandInputId() != null && this
				.getActionCommandInputId().equals(castOther.getActionCommandInputId())))
				&& ((this.getParamInputId() == castOther.getParamInputId()) || (this.getParamInputId() != null && castOther.getParamInputId() != null && this.getParamInputId().equals(
						castOther.getParamInputId())))
				
				&& ((this.getActionFlowInId() == castOther.getActionFlowInId()) || (this.getActionFlowInId() != null && castOther.getActionFlowInId() != null && this.getActionFlowInId().equals(
						castOther.getActionFlowInId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getActionCommandInputId() == null ? 0 : this.getActionCommandInputId().hashCode());
		result = 37 * result + (getParamInputId() == null ? 0 : this.getParamInputId().hashCode());
		result = 37 * result + (getActionFlowInId() == null ? 0 : this.getActionFlowInId().hashCode());
		return result;
	}

}
