package com.viettel.it.model;
// Generated Nov 9, 2016 3:21:19 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlanIpVirtualEthernet generated by hbm2java
 */
@Entity
@Table(name = "PLAN_IP_VIRTUAL_ETHERNET")
public class PlanIpVirtualEthernet implements java.io.Serializable {

	private Long id;
	private String areaCode;
	private String ipL2;
	private String ipL2Subring;
	private Long curIdex;

	public PlanIpVirtualEthernet() {
	}

	public PlanIpVirtualEthernet(Long id) {
		this.id = id;
	}
	public PlanIpVirtualEthernet(Long id, String areaCode, String ipL2, String ipL2Subring) {
		this.id = id;
		this.areaCode = areaCode;
		this.ipL2 = ipL2;
		this.ipL2Subring = ipL2Subring;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "AREA_CODE", length = 20)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "IP_L2", length = 20)
	public String getIpL2() {
		return this.ipL2;
	}

	public void setIpL2(String ipL2) {
		this.ipL2 = ipL2;
	}

	@Column(name = "IP_L2_SUBRING", length = 20)
	public String getIpL2Subring() {
		return this.ipL2Subring;
	}

	public void setIpL2Subring(String ipL2Subring) {
		this.ipL2Subring = ipL2Subring;
	}
	@Column(name = "CUR_IDEX", precision = 22, scale = 0)
	public Long getCurIdex() {
		return this.curIdex;
	}

	public void setCurIdex(Long curIdex) {
		this.curIdex = curIdex;
	}

}
