package com.viettel.it.model;
// Generated Nov 14, 2016 8:41:05 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

/**
 * RescueInfoPlan generated by hbm2java
 */
@Entity
@Table(name = "RESCUE_INFO_PLAN", schema = "AUTOACCESS")
public class RescueInfoPlan implements java.io.Serializable {

	private Long id;
	private Long rnc;
	private Long sgsnCurrent;
	private Long sauRnc;
	private Long pdpRnc;
	private Long sauSgsnCurrent;
	private Long pdpSgsnCurrent;
	private Long sgsnBackup;
	private Long sauSgsnBackup;
	private Long pdpSgsnBackup;
	private Long saurSgsnCurrent;
	private Long pdprSgsnCurrent;
	private Long saurSgsnBackup;
	private Long pdprSgsnBackup;
	private Date updateTime;
	private Long autoCheck;
	private String backOfficeEngineer;
	private String approveManager;

	public RescueInfoPlan() {
	}

	public RescueInfoPlan(Long id) {
		this.id = id;
	}
	public RescueInfoPlan(Long id, Long rnc, Long sgsnCurrent, Long sauRnc, Long pdpRnc, Long sauSgsnCurrent, Long pdpSgsnCurrent, Long sgsnBackup, Long sauSgsnBackup,
			Long pdpSgsnBackup, Long saurSgsnCurrent, Long pdprSgsnCurrent, Long saurSgsnBackup, Long pdprSgsnBackup, Date updateTime, Long autoCheck, String backOfficeEngineer,
			String approveManager) {
		this.id = id;
		this.rnc = rnc;
		this.sgsnCurrent = sgsnCurrent;
		this.sauRnc = sauRnc;
		this.pdpRnc = pdpRnc;
		this.sauSgsnCurrent = sauSgsnCurrent;
		this.pdpSgsnCurrent = pdpSgsnCurrent;
		this.sgsnBackup = sgsnBackup;
		this.sauSgsnBackup = sauSgsnBackup;
		this.pdpSgsnBackup = pdpSgsnBackup;
		this.saurSgsnCurrent = saurSgsnCurrent;
		this.pdprSgsnCurrent = pdprSgsnCurrent;
		this.saurSgsnBackup = saurSgsnBackup;
		this.pdprSgsnBackup = pdprSgsnBackup;
		this.updateTime = updateTime;
		this.autoCheck = autoCheck;
		this.backOfficeEngineer = backOfficeEngineer;
		this.approveManager = approveManager;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RNC", precision = 20, scale = 0)
	public Long getRnc() {
		return this.rnc;
	}

	public void setRnc(Long rnc) {
		this.rnc = rnc;
	}

	@Column(name = "SGSN_CURRENT", precision = 20, scale = 0)
	public Long getSgsnCurrent() {
		return this.sgsnCurrent;
	}

	public void setSgsnCurrent(Long sgsnCurrent) {
		this.sgsnCurrent = sgsnCurrent;
	}

	@Column(name = "SAU_RNC", precision = 20, scale = 0)
	public Long getSauRnc() {
		return this.sauRnc;
	}

	public void setSauRnc(Long sauRnc) {
		this.sauRnc = sauRnc;
	}

	@Column(name = "PDP_RNC", precision = 20, scale = 0)
	public Long getPdpRnc() {
		return this.pdpRnc;
	}

	public void setPdpRnc(Long pdpRnc) {
		this.pdpRnc = pdpRnc;
	}

	@Column(name = "SAU_SGSN_CURRENT", precision = 20, scale = 0)
	public Long getSauSgsnCurrent() {
		return this.sauSgsnCurrent;
	}

	public void setSauSgsnCurrent(Long sauSgsnCurrent) {
		this.sauSgsnCurrent = sauSgsnCurrent;
	}

	@Column(name = "PDP_SGSN_CURRENT", precision = 20, scale = 0)
	public Long getPdpSgsnCurrent() {
		return this.pdpSgsnCurrent;
	}

	public void setPdpSgsnCurrent(Long pdpSgsnCurrent) {
		this.pdpSgsnCurrent = pdpSgsnCurrent;
	}

	@Column(name = "SGSN_BACKUP", precision = 20, scale = 0)
	public Long getSgsnBackup() {
		return this.sgsnBackup;
	}

	public void setSgsnBackup(Long sgsnBackup) {
		this.sgsnBackup = sgsnBackup;
	}

	@Column(name = "SAU_SGSN_BACKUP", precision = 20, scale = 0)
	public Long getSauSgsnBackup() {
		return this.sauSgsnBackup;
	}

	public void setSauSgsnBackup(Long sauSgsnBackup) {
		this.sauSgsnBackup = sauSgsnBackup;
	}

	@Column(name = "PDP_SGSN_BACKUP", precision = 20, scale = 0)
	public Long getPdpSgsnBackup() {
		return this.pdpSgsnBackup;
	}

	public void setPdpSgsnBackup(Long pdpSgsnBackup) {
		this.pdpSgsnBackup = pdpSgsnBackup;
	}

	@Column(name = "SAUR_SGSN_CURRENT", precision = 20, scale = 0)
	public Long getSaurSgsnCurrent() {
		return this.saurSgsnCurrent;
	}

	public void setSaurSgsnCurrent(Long saurSgsnCurrent) {
		this.saurSgsnCurrent = saurSgsnCurrent;
	}

	@Column(name = "PDPR_SGSN_CURRENT", precision = 20, scale = 0)
	public Long getPdprSgsnCurrent() {
		return this.pdprSgsnCurrent;
	}

	public void setPdprSgsnCurrent(Long pdprSgsnCurrent) {
		this.pdprSgsnCurrent = pdprSgsnCurrent;
	}

	@Column(name = "SAUR_SGSN_BACKUP", precision = 20, scale = 0)
	public Long getSaurSgsnBackup() {
		return this.saurSgsnBackup;
	}

	public void setSaurSgsnBackup(Long saurSgsnBackup) {
		this.saurSgsnBackup = saurSgsnBackup;
	}

	@Column(name = "PDPR_SGSN_BACKUP", precision = 20, scale = 0)
	public Long getPdprSgsnBackup() {
		return this.pdprSgsnBackup;
	}

	public void setPdprSgsnBackup(Long pdprSgsnBackup) {
		this.pdprSgsnBackup = pdprSgsnBackup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "AUTO_CHECK", precision = 2, scale = 0)
	public Long getAutoCheck() {
		return this.autoCheck;
	}

	public void setAutoCheck(Long autoCheck) {
		this.autoCheck = autoCheck;
	}

	@Column(name = "BACK_OFFICE_ENGINEER", length = 200)
	public String getBackOfficeEngineer() {
		return this.backOfficeEngineer;
	}

	public void setBackOfficeEngineer(String backOfficeEngineer) {
		this.backOfficeEngineer = backOfficeEngineer;
	}

	@Column(name = "APPROVE_MANAGER", length = 200)
	public String getApproveManager() {
		return this.approveManager;
	}

	public void setApproveManager(String approveManager) {
		this.approveManager = approveManager;
	}

}
