package com.viettel.it.model;
// Generated Oct 28, 2016 8:58:39 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceTemplateId generated by hbm2java
 */
@Embeddable
public class ServiceTemplateId implements java.io.Serializable {

	private Long flowTemplateId;
	private Long vendorId;
	private Long versionId;
	private Long serviceCode;
	private Long action;
	private Long subring;
	private String provinceCode;

	public ServiceTemplateId() {
	}

	public ServiceTemplateId(Long flowTemplateId, Long vendorId, Long versionId, Long serviceCode, Long action) {
		this.flowTemplateId = flowTemplateId;
		this.vendorId = vendorId;
		this.versionId = versionId;
		this.serviceCode = serviceCode;
		this.action = action;
	}

	@Column(name = "FLOW_TEMPLATE_ID", nullable = false, precision = 22, scale = 0)
	public Long getFlowTemplateId() {
		return this.flowTemplateId;
	}

	public void setFlowTemplateId(Long flowTemplateId) {
		this.flowTemplateId = flowTemplateId;
	}

	@Column(name = "VENDOR_ID", nullable = false, precision = 22, scale = 0)
	public Long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Long vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "VERSION_ID", nullable = false, precision = 22, scale = 0)
	public Long getVersionId() {
		return this.versionId;
	}

	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	@Column(name = "SERVICE_CODE", nullable = false, precision = 22, scale = 0)
	public Long getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(Long serviceCode) {
		this.serviceCode = serviceCode;
	}

	@Column(name = "ACTION", nullable = false, precision = 22, scale = 0)
	public Long getAction() {
		return this.action;
	}

	public void setAction(Long action) {
		this.action = action;
	}
	@Column(name="PROVINCE_CODE")
	public String getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name="IS_SUBRING")
	public Long getSubring() {
		return subring;
	}

	public void setSubring(Long subring) {
		this.subring = subring;
	}

	 

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((action == null) ? 0 : action.hashCode());
		result = prime * result + ((flowTemplateId == null) ? 0 : flowTemplateId.hashCode());
		result = prime * result + ((provinceCode == null) ? 0 : provinceCode.hashCode());
		result = prime * result + ((serviceCode == null) ? 0 : serviceCode.hashCode());
		result = prime * result + ((subring == null) ? 0 : subring.hashCode());
		result = prime * result + ((vendorId == null) ? 0 : vendorId.hashCode());
		result = prime * result + ((versionId == null) ? 0 : versionId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ServiceTemplateId other = (ServiceTemplateId) obj;
		if (action == null) {
			if (other.action != null)
				return false;
		} else if (!action.equals(other.action))
			return false;
		if (flowTemplateId == null) {
			if (other.flowTemplateId != null)
				return false;
		} else if (!flowTemplateId.equals(other.flowTemplateId))
			return false;
		if (provinceCode == null) {
			if (other.provinceCode != null)
				return false;
		} else if (!provinceCode.equals(other.provinceCode))
			return false;
		if (serviceCode == null) {
			if (other.serviceCode != null)
				return false;
		} else if (!serviceCode.equals(other.serviceCode))
			return false;
		if (subring == null) {
			if (other.subring != null)
				return false;
		} else if (!subring.equals(other.subring))
			return false;
		if (vendorId == null) {
			if (other.vendorId != null)
				return false;
		} else if (!vendorId.equals(other.vendorId))
			return false;
		if (versionId == null) {
			if (other.versionId != null)
				return false;
		} else if (!versionId.equals(other.versionId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ServiceTemplateId [" + (flowTemplateId != null ? "flowTemplateId=" + flowTemplateId + ", " : "") + (vendorId != null ? "vendorId=" + vendorId + ", " : "")
				+ (versionId != null ? "versionId=" + versionId + ", " : "") + (serviceCode != null ? "serviceCode=" + serviceCode + ", " : "")
				+ (action != null ? "action=" + action + ", " : "") + (subring != null ? "subring=" + subring + ", " : "")
				+ (provinceCode != null ? "provinceCode=" + provinceCode : "") + "]";
	}

	 
	
}
