package com.viettel.it.model;
// Generated Oct 28, 2016 8:58:39 AM by Hibernate Tools 4.0.0

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.persistence.*;
import java.util.List;

/**
 * ServiceTemplate generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_TEMPLATE",uniqueConstraints = @UniqueConstraint(columnNames = {"VENDOR_ID", "VERSION_ID", "SERVICE_CODE", "ACTION"}))
public class ServiceTemplate implements java.io.Serializable {
	private static Logger logger = LogManager.getLogger(ServiceTemplate.class);

	private ServiceTemplateId id;
	private Version version;
	private FlowTemplates flowTemplates;
	private Vendor vendor;
	private List<String> provinceCodes;
	
	public ServiceTemplate() {
	}

	public ServiceTemplate(ServiceTemplateId id, Version version, FlowTemplates flowTemplates, Vendor vendor) {
		this.id = id;
		this.version = version;
		this.flowTemplates = flowTemplates;
		this.vendor = vendor;
	}

	@EmbeddedId
	@AttributeOverrides({@AttributeOverride(name = "flowTemplateId", column = @Column(name = "FLOW_TEMPLATE_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "vendorId", column = @Column(name = "VENDOR_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "versionId", column = @Column(name = "VERSION_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "serviceCode", column = @Column(name = "SERVICE_CODE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "action", column = @Column(name = "ACTION", nullable = false, precision = 22, scale = 0))})
	public ServiceTemplateId getId() {
		return this.id;
	}

	public void setId(ServiceTemplateId id) {
		this.id = id;
	}

	@ManyToOne( )
	@JoinColumn(name = "VERSION_ID", nullable = false, insertable = false, updatable = false)
	public Version getVersion() {
		return this.version;
	}

	public void setVersion(Version version) {
		this.version = version;
	}

	@ManyToOne( )
	@JoinColumn(name = "FLOW_TEMPLATE_ID", nullable = false, insertable = false, updatable = false)
	public FlowTemplates getFlowTemplates() {
		return this.flowTemplates;
	}

	public void setFlowTemplates(FlowTemplates flowTemplates) {
		this.flowTemplates = flowTemplates;
	}

	@ManyToOne( )
	@JoinColumn(name = "VENDOR_ID", nullable = false, insertable = false, updatable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Override
	public String toString() {
		try {
			return flowTemplates.getFlowTemplateName()+", "+vendor.getVendorName()+", "+version.getVersionName()+
					", "+id.getServiceCode()+", "+id.getAction();
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
		}
		return null;
	}

	

	@Transient
	public List<String> getProvinceCodes() {
		return provinceCodes;
	}

	public void setProvinceCodes(List<String> provinceCodes) {
		this.provinceCodes = provinceCodes;
	}

	
}
