package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0

import com.viettel.it.object.TbsNodeObj;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "V_DATABASE_INFOS")
public class VDatabaseInfos implements java.io.Serializable {

	private String vId;
	private String dbId;
	private String serviceName;
	private String jdbcUrl;
	private Integer port;
	private String listIp;
	private String listIpVirtual;
	private String impactTimes;
	private String addParTime;
	private String addTbsTime;
	private String addDatafileTime;
	private String dropParTime;
	private String resizeTbsTime;
	private String exportTbsTime;
	private String userManager;
	
	// for display export
	private List<String> lstNodeIpServer = new ArrayList<>();
	private String selectedNodeIpImpact;

	// for display add datafile
	private List<TbsNodeObj> lstTbsObj = new ArrayList<>();
	private List<String> lstTbsName = new ArrayList<>();
	private List<String> lstTbsNameSelected = new ArrayList<>();
	private String tbsNameSelected;
	private Integer numOfDatafile;
	private TbsNodeObj tbsObjSelected;

	/*20181210_hoangnd_them active_start*/
	private Long active;

	@Column(name = "ACTIVE")
	public Long getActive() {
		return active;
	}

	public void setActive(Long active) {
		this.active = active;
	}
	/*20181210_hoangnd_them active_end*/

	public VDatabaseInfos() {
		super();
	}

	@Id
	@Column(name = "V_ID", length = 200)
	public String getvId() {
		return vId;
	}

	public void setvId(String vId) {
		this.vId = vId;
	}
	
	@Column(name = "DB_ID", length = 200)
	public String getDbId() {
		return dbId;
	}

	public void setDbId(String dbId) {
		this.dbId = dbId;
	}

	@Column(name = "SERVICE_NAME", length = 200)
	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "JDBC_URL", length = 200)
	public String getJdbcUrl() {
		return jdbcUrl;
	}

	public void setJdbcUrl(String jdbcUrl) {
		this.jdbcUrl = jdbcUrl;
	}

	@Column(name = "PORT", precision = 7)
	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}
	
	@Column(name = "LIST_IP", length = 200)
	public String getListIp() {
		return listIp;
	}

	public void setListIp(String listIp) {
		this.listIp = listIp;
	}

	@Column(name = "LIST_IP_VIRTUAL", length = 200)
	public String getListIpVirtual() {
		return listIpVirtual;
	}

	public void setListIpVirtual(String listIpVirtual) {
		this.listIpVirtual = listIpVirtual;
	}
	
	@Column(name = "IMPACT_TIMES", length = 200)
	public String getImpactTimes() {
		return impactTimes;
	}

	public void setImpactTimes(String impactTimes) {
		this.impactTimes = impactTimes;
	}
	
	@Column(name = "ADD_PAR_TIME", length = 200)
	public String getAddParTime() {
		return addParTime;
	}

	public void setAddParTime(String addParTime) {
		this.addParTime = addParTime;
	}

	@Column(name = "ADD_TBS_TIME", length = 200)
	public String getAddTbsTime() {
		return addTbsTime;
	}

	public void setAddTbsTime(String addTbsTime) {
		this.addTbsTime = addTbsTime;
	}

	@Column(name = "ADD_DATAFILE_TIME", length = 200)
	public String getAddDatafileTime() {
		return addDatafileTime;
	}

	public void setAddDatafileTime(String addDatafileTime) {
		this.addDatafileTime = addDatafileTime;
	}

	@Column(name = "DROP_PAR_TIME", length = 200)
	public String getDropParTime() {
		return dropParTime;
	}

	public void setDropParTime(String dropParTime) {
		this.dropParTime = dropParTime;
	}

	@Column(name = "RESIZE_TBS_TIME", length = 200)
	public String getResizeTbsTime() {
		return resizeTbsTime;
	}

	public void setResizeTbsTime(String resizeTbsTime) {
		this.resizeTbsTime = resizeTbsTime;
	}

	@Column(name = "EXPORT_TBS_TIME", length = 200)
	public String getExportTbsTime() {
		return exportTbsTime;
	}

	public void setExportTbsTime(String exportTbsTime) {
		this.exportTbsTime = exportTbsTime;
	}

	@Column(name = "USER_MANAGER", length = 200)
	public String getUserManager() {
		return userManager;
	}

	public void setUserManager(String userManager) {
		this.userManager = userManager;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((vId == null) ? 0 : vId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		VDatabaseInfos other = (VDatabaseInfos) obj;
		if (vId == null) {
			if (other.vId != null)
				return false;
		} else if (!vId.equals(other.vId))
			return false;
		return true;
	}


	@Transient
	public List<String> getLstNodeIpServer() {
		return lstNodeIpServer;
	}

	public void setLstNodeIpServer(List<String> lstNodeIpServer) {
		this.lstNodeIpServer = lstNodeIpServer;
	}

	@Transient
	public String getSelectedNodeIpImpact() {
		return selectedNodeIpImpact;
	}

	public void setSelectedNodeIpImpact(String selectedNodeIpImpact) {
		this.selectedNodeIpImpact = selectedNodeIpImpact;
	}

    @Transient
    public List<String> getLstTbsName() {
        return lstTbsName;
    }

    public void setLstTbsName(List<String> lstTbsName) {
        this.lstTbsName = lstTbsName;
    }

    @Transient
    public String getTbsNameSelected() {
        return tbsNameSelected;
    }

    public void setTbsNameSelected(String tbsNameSelected) {
        this.tbsNameSelected = tbsNameSelected;
    }

    @Transient
    public Integer getNumOfDatafile() {
        return numOfDatafile;
    }

    public void setNumOfDatafile(Integer numOfDatafile) {
        this.numOfDatafile = numOfDatafile;
    }

	@Transient
	public List<TbsNodeObj> getLstTbsObj() {
		return lstTbsObj;
	}

	public void setLstTbsObj(List<TbsNodeObj> lstTbsObj) {
		this.lstTbsObj = lstTbsObj;
	}

	@Transient
	public TbsNodeObj getTbsObjSelected() {
		return tbsObjSelected;
	}

	public void setTbsObjSelected(TbsNodeObj tbsObjSelected) {
		this.tbsObjSelected = tbsObjSelected;
	}

	@Transient
	public List<String> getLstTbsNameSelected() {
		return lstTbsNameSelected;
	}

	public void setLstTbsNameSelected(List<String> lstTbsNameSelected) {
		this.lstTbsNameSelected = lstTbsNameSelected;
	}
}
