package com.viettel.it.model;

// Generated Sep 8, 2016 5:07:30 PM by Hibernate Tools 4.0.0


import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * Vendor generated by hbm2java
 */
@Entity
@Table(name = "VENDOR")
public class Vendor implements java.io.Serializable {

	private Long vendorId;
	private String vendorName;
	private String description;
	private List<Node> nodes = new ArrayList<Node>(0);
//	private List<ActionDetail> actionDetails = new ArrayList<ActionDetail>(0);
	private List<CommandDetail> commandDetails = new ArrayList<CommandDetail>(0);

    public Vendor() {
    }


    @Id
    @Column(name = "VENDOR_ID", unique = true, nullable = false, precision = 10, scale = 0)
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @SequenceGenerator(name = "generator", sequenceName = "VENDOR_SEQ", allocationSize = 1)
    public Long getVendorId() {
        return this.vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Column(name = "VENDOR_NAME", nullable = false, length = 600)
    public String getVendorName() {
        return this.vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    @Column(name = "DESCRIPTION", length = 1500)
    public String getDescription() {
        return this.description;
    }

	//@OneToMany(fetch = FetchType.EAGER, mappedBy = "vendor")
	//@LazyCollection(LazyCollectionOption.EXTRA)
	@Transient
	public List<Node> getNodes() {
		return this.nodes;
	}

	public void setNodes(List<Node> nodes) {
		this.nodes = nodes;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vendor")
//	public List<ActionDetail> getActionDetails() {
//		return this.actionDetails;
//	}
//
//	public void setActionDetails(List<ActionDetail> actionDetails) {
//		this.actionDetails = actionDetails;
//	}

	//@OneToMany(fetch = FetchType.EAGER, mappedBy = "vendor")
	//@LazyCollection(LazyCollectionOption.EXTRA)
	@Transient
	public List<CommandDetail> getCommandDetails() {
		return this.commandDetails;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	public void setCommandDetails(List<CommandDetail> commandDetails) {
		this.commandDetails = commandDetails;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((vendorId == null) ? 0 : vendorId.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Vendor other = (Vendor) obj;
		if (vendorId == null) {
			if (other.vendorId != null)
				return false;
		} else if (!vendorId.equals(other.vendorId))
			return false;
		return true;
	}


	@Override
	public String toString() {
		return "Vendor [vendorName=" + vendorName + "]";
	}
	
	
	
}
